<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SmokeTestWeb</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>373f4ece-ff17-4ba9-b9f0-e5c1ba8a9dd9</testSuiteGuid>
   <testCaseLink>
      <guid>7e323788-8f47-4bca-8461-6511fb396a4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUp/MO001_SignUpW_HighSchoolStudent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d2c0aa-1de1-4f32-b276-7d6645387412</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c2b3cb1-ea73-4cc8-94a5-d6a405aa4960</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f5d5242-4b2e-420e-8402-b35157fd395d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1bfe733d-6f1e-45dd-8c36-5867a3e70e72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUp/MO002_SignUpW_TransferStudent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bceb80c-bd96-4be7-a68a-652d9370e3e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d40af388-8e19-44d3-a39b-8b90d7d96025</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc8a714a-42a7-4cfd-ab17-c25f9cf6a9a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5eb92d50-2d2a-4fb1-9cb4-56305028a9cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUp/MO003_SignUpW_AdultLearner</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13a6bb62-29ae-4c5c-8515-36f685b4c388</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db68a69b-2541-4c44-b09b-eab02c392182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16985a27-27e0-4210-b950-294581a1caa1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>929a111b-a629-47b1-95e5-3565853bf953</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUp/MO004_SignUpW_Parent</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97b999a3-aa97-478f-8873-c93fa3f94d26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b68052f7-fa65-4b51-9e4f-28f76601123b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b6c7189-1a08-48bb-91f8-64d8c43c98be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ebeee46-8b83-4dbc-9da9-6286733648e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUp/MO005_SignUpW_SchoolCounselor</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1641e931-6a7c-4a0d-b547-fcd403fe9d7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c158b9ee-d2b5-42ce-9189-3e53fecabb57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0a68a55-3403-468b-932e-27d518d1185a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
